// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7tUZp8Daz0Sekc7PQtubLgizd9Jqam1I',
    appId: '1:178848094963:web:04daae8fc0c88143147586',
    messagingSenderId: '178848094963',
    projectId: 'areyes17-fanpage-app',
    authDomain: 'areyes17-fanpage-app.firebaseapp.com',
    storageBucket: 'areyes17-fanpage-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAG1lsfkxIqlmzui0UNxnVWKfDHn1QPjzU',
    appId: '1:178848094963:android:e21850b155ab6473147586',
    messagingSenderId: '178848094963',
    projectId: 'areyes17-fanpage-app',
    storageBucket: 'areyes17-fanpage-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCskjh88CY385ieS5SjCIgnB3riuOkjke4',
    appId: '1:178848094963:ios:901f21d4fe24e16c147586',
    messagingSenderId: '178848094963',
    projectId: 'areyes17-fanpage-app',
    storageBucket: 'areyes17-fanpage-app.appspot.com',
    iosClientId: '178848094963-a8o3shu5pfdhibi8b9fcmcf8aeas4arn.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
